### ISSUE TITLE
Permission and 404 error

### ISSUE THREAD

**Issue by xyluz** [wordpress-clients/wp-api-angular#33]
![screen shot 2017-08-29 at 16 35 34](https://user-images.githubusercontent.com/13081285/29829852-693c5d9a-8cd8-11e7-9d00-49c93f95d739.png)
Hi, I followed this tutorial:

https://devdactic.com/ionic-wordpress-api/ everything seems fine, but the articles don't load..

I get this error:

"{"code":"itsec_rest_api_access_restricted","message":"You do not have sufficient permission to access this endpoint. Access to REST API requests is restricted by iThemes Security settings.","data":null}

I went into my WordPress installation to change the security settings to default.

Then I got this error:

Runtime Error
Cannot read property 'length' of undefined

---------stack trace -------
TypeError: Cannot read property 'length' of undefined
    at WpProvider.webpackJsonp.594.WpProvider.getUserImage (http://localhost:8100/build/main.js:381:50)
    at NewsTabPage.webpackJsonp.273.NewsTabPage.getUserImage (http://localhost:8100/build/1.js:74:32)
    at Object.eval [as updateRenderer] (ng:///NewsTabPageModule/NewsTabPage.ngfactory.js:170:24)
    at Object.debugUpdateRenderer [as updateRenderer] (http://localhost:8100/build/vendor.js:13204:21)
    at checkAndUpdateView (http://localhost:8100/build/vendor.js:12509:14)
    at callViewAction (http://localhost:8100/build/vendor.js:12867:21)
    at execEmbeddedViewsAction (http://localhost:8100/build/vendor.js:12825:17)
    at checkAndUpdateView (http://localhost:8100/build/vendor.js:12505:5)
    at callViewAction (http://localhost:8100/build/vendor.js:12867:21)
    at execComponentViewsAction (http://localhost:8100/build/vendor.js:12799:13)

----------------

Can you help solve this?

**Comment by shprink** [comment]
hello,

what version of this lib and angular do you use? The tutorial you followed is old and a new version exists now.

**Comment by xyluz** [comment]
oh, wow... I think the lib version will be the latest because I just got it yesterday... am working with ionic 3.9.2.
What do you recommend I do?

**Comment by shprink** [comment]
I recommend you forget about this tutorial and read the README to use this lib correctly. If you still have problems please re-open this ticket ;) thanks
