### ISSUE TITLE
Error building project | Types of property 'X' are incompatible.

### ISSUE THREAD

**Issue by karrirasinmaki** [wordpress-clients/wp-api-angular#35]
Hey,

I am trying to contribute to your project. However the project won't build but showing errors. Console log below.

( I did run ``npm install`` before.)

```

karrirasinmaki@thinkpadrioX1:~/dev/io/app/app/node_modules/wp-api-angular% npm run build

> wp-api-angular@3.0.0-beta8 prebuild /home/karrirasinmaki/dev/io/app/app/node_modules/wp-api-angular
> rm -rf dist


> wp-api-angular@3.0.0-beta8 build /home/karrirasinmaki/dev/io/app/app/node_modules/wp-api-angular
> node ./node_modules/@angular/compiler-cli/src/main.js && npm run dumpdev && npm run dumpprod

Error at /home/karrirasinmaki/dev/io/app/app/node_modules/wp-api-angular/src/Parent.ts:24:14: Class 'WpApiParent' incorrectly implements interface 'IParent'.
  Types of property 'httpGet' are incompatible.
    Type '(url: string, options?: {}) => Observable<Response>' is not assignable to type '(url: string, options?: RequestOptionsArgs) => Observable<Response>'.
      Type 'Observable<Response>' is not assignable to type 'Observable<Response>'. Two different types with this name exist, but they are unrelated.
        Property 'pipe' is missing in type 'Observable<Response>'.
Error at /home/karrirasinmaki/dev/io/app/app/node_modules/wp-api-angular/src/Posts.ts:31:14: Class 'WpApiPosts' incorrectly implements interface 'IWpApiPosts'.
  Types of property 'getList' are incompatible.
    Type '(options?: {}) => Observable<Response>' is not assignable to type '(options?: RequestOptionsArgs) => Observable<Response>'.
      Type 'Observable<Response>' is not assignable to type 'Observable<Response>'. Two different types with this name exist, but they are unrelated.
Error at /home/karrirasinmaki/dev/io/app/app/node_modules/wp-api-angular/src/Pages.ts:27:14: Class 'WpApiPages' incorrectly implements interface 'IWpApiPages'.
  Types of property 'getList' are incompatible.
    Type '(options?: {}) => Observable<Response>' is not assignable to type '(options?: RequestOptionsArgs) => Observable<Response>'.
      Type 'Observable<Response>' is not assignable to type 'Observable<Response>'. Two different types with this name exist, but they are unrelated.
Error at /home/karrirasinmaki/dev/io/app/app/node_modules/wp-api-angular/src/Comments.ts:22:14: Class 'WpApiComments' incorrectly implements interface 'IWpApiComments'.
  Types of property 'getList' are incompatible.
    Type '(options?: {}) => Observable<Response>' is not assignable to type '(options?: RequestOptionsArgs) => Observable<Response>'.
      Type 'Observable<Response>' is not assignable to type 'Observable<Response>'. Two different types with this name exist, but they are unrelated.
Error at /home/karrirasinmaki/dev/io/app/app/node_modules/wp-api-angular/src/Types.ts:20:14: Class 'WpApiTypes' incorrectly implements interface 'IWpApiTypes'.
  Types of property 'getList' are incompatible.
    Type '(options?: {}) => Observable<Response>' is not assignable to type '(options?: RequestOptionsArgs) => Observable<Response>'.
      Type 'Observable<Response>' is not assignable to type 'Observable<Response>'. Two different types with this name exist, but they are unrelated.
Error at /home/karrirasinmaki/dev/io/app/app/node_modules/wp-api-angular/src/Media.ts:23:14: Class 'WpApiMedia' incorrectly implements interface 'IWpApiMedia'.
  Types of property 'getList' are incompatible.
    Type '(options?: {}) => Observable<Response>' is not assignable to type '(options?: RequestOptionsArgs) => Observable<Response>'.
      Type 'Observable<Response>' is not assignable to type 'Observable<Response>'. Two different types with this name exist, but they are unrelated.
Error at /home/karrirasinmaki/dev/io/app/app/node_modules/wp-api-angular/src/Users.ts:24:14: Class 'WpApiUsers' incorrectly implements interface 'IWpApiUsers'.
  Types of property 'getList' are incompatible.
    Type '(options?: {}) => Observable<Response>' is not assignable to type '(options?: RequestOptionsArgs) => Observable<Response>'.
      Type 'Observable<Response>' is not assignable to type 'Observable<Response>'. Two different types with this name exist, but they are unrelated.
Error at /home/karrirasinmaki/dev/io/app/app/node_modules/wp-api-angular/src/Taxonomies.ts:20:14: Class 'WpApiTaxonomies' incorrectly implements interface 'IWpApiTaxonomies'.
  Types of property 'getList' are incompatible.
    Type '(options?: {}) => Observable<Response>' is not assignable to type '(options?: RequestOptionsArgs) => Observable<Response>'.
      Type 'Observable<Response>' is not assignable to type 'Observable<Response>'. Two different types with this name exist, but they are unrelated.
Error at /home/karrirasinmaki/dev/io/app/app/node_modules/wp-api-angular/src/Statuses.ts:20:14: Class 'WpApiStatuses' incorrectly implements interface 'IWpApiStatuses'.
  Types of property 'getList' are incompatible.
    Type '(options?: {}) => Observable<Response>' is not assignable to type '(options?: RequestOptionsArgs) => Observable<Response>'.
      Type 'Observable<Response>' is not assignable to type 'Observable<Response>'. Two different types with this name exist, but they are unrelated.
Error at /home/karrirasinmaki/dev/io/app/app/node_modules/wp-api-angular/src/Terms.ts:25:14: Class 'WpApiTerms' incorrectly implements interface 'IWpApiTerms'.
  Types of property 'getList' are incompatible.
    Type '(taxonomiesType?: string, options?: {}) => Observable<Response>' is not assignable to type '(taxonomiesType: string, options?: RequestOptionsArgs) => Observable<Response>'.
      Type 'Observable<Response>' is not assignable to type 'Observable<Response>'. Two different types with this name exist, but they are unrelated.
Error at /home/karrirasinmaki/dev/io/app/app/node_modules/wp-api-angular/src/Custom.ts:22:14: Class 'Custom' incorrectly implements interface 'IWpApiCustom'.
  Types of property 'getList' are incompatible.
    Type '(options?: {}) => Observable<Response>' is not assignable to type '(options?: RequestOptionsArgs) => Observable<Response>'.
      Type 'Observable<Response>' is not assignable to type 'Observable<Response>'. Two different types with this name exist, but they are unrelated.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wp-api-angular@3.0.0-beta8 build: `node ./node_modules/@angular/compiler-cli/src/main.js && npm run dumpdev && npm run dumpprod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wp-api-angular@3.0.0-beta8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by karrirasinmaki** [comment]
Ok, I do not quite remember how I fixed this issue for me, but it is not bothering me anymore. Therefore closing.
